POLYGON_CONFIG_FILE_NAME = 'problem.xml'

POLYGON_CONFIG_PROBLEM_TITLE = 'names.name'

POLYGON_CONFIG_STATEMENTS = 'statements'
POLYGON_CONFIG_STATEMENT = 'statement'
POLYGON_CONFIG_STATEMENT_TEX_TYPE = 'application/x-tex'

POLYGON_CONFIG_TIME_LIMIT = 'judging.testset.time-limit'
POLYGON_CONFIG_DEFAULT_TIME_LIMIT = 1000

POLYGON_CONFIG_MEMORY_LIMIT = 'judging.testset.memory-limit'
POLYGON_CONFIG_DEFAULT_MEMORY_LIMIT = 128 * 1024 * 1024

POLYGON_CONFIG_TEST_COUNT = 'judging.testset.test-count'
POLYGON_CONFIG_DEFAULT_TEST_COUNT = 0

POLYGON_CONFIG_TEST_BASE_INDEX = 1

POLYGON_CONFIG_TESTSET = 'judging.testset'
POLYGON_CONFIG_TESTS = 'tests'
POLYGON_CONFIG_TEST = 'test'
POLYGON_CONFIG_TEST_GROUP = 'group'
POLYGON_CONFIG_INPUT_PATH_PATTERN = 'input-path-pattern'
POLYGON_CONFIG_DEFAULT_INPUT_PATH_PATTERN = 'tests/%02d'

POLYGON_CONFIG_GROUPS = 'judging.testset.groups'
POLYGON_CONFIG_GROUP = 'group'
POLYGON_CONFIG_DEPENDENCIES = 'dependencies'
POLYGON_CONFIG_DEPENDENCY = 'dependency'

POLYGON_CONFIG_EXECUTABLES = 'files.executables'
POLYGON_CONFIG_EXECUTABLE = 'executable'
POLYGON_CONFIG_EXECUTABLE_SOURCE = 'source'

POLYGON_CONFIG_CHECKER = 'assets.checker.source'

POLYGON_CONFIG_VALIDATORS = 'assets.validators'
POLYGON_CONFIG_VALIDATOR = 'validator'
POLYGON_CONFIG_VALIDATOR_SOURCE = 'source'

POLYGON_CONFIG_SOLUTIONS = 'assets.solutions'
POLYGON_CONFIG_SOLUTION = 'solution'
POLYGON_CONFIG_SOLUTION_SOURCE = 'source'

POLYGON_CONFIG_GENERATOR_METHOD = 'method'
POLYGON_CONFIG_GENERATOR_METHOD_MANUAL = 'manual'
POLYGON_CONFIG_GENERATOR_METHOD_GENERATED = 'generated'
POLYGON_CONFIG_GENERATOR_GENSCRIPT = 'cmd'
POLYGON_CONFIG_GENERATOR_IS_EXAMPLE = 'sample'
POLYGON_CONFIG_GENERATOR_DESCRIPTION = 'description'

POLYGON_CONFIG_PPS_CUSTROM_MANUAL_GENERATOR = '__pps_generator'



PPS_FS_STATEMENT_PATH = 'statement'
PPS_FS_CHECKER_PATH = 'checker'
PPS_FS_GENERATOR_PATH = 'generator'
PPS_FS_SOLUTION_PATH = 'solution'
PPS_FS_VALIDATOR_PATH = 'validator'

PPS_FS_CONFIG_NAME = 'config.json'